name: OAKillCmd
version: ${project.version}
main: net.pistonmaster.oakillcmd.OAKillCmd
api-version: 1.13
author: AlexProgrammerDE
description: Kill, but with cooldown!

commands:
  kill:
    description: Command to kill yourself.
    usage: /kill
